site status management for movies
marcin10lw/movies-browser pull request #23
Opened 2023-03-02 13:22 UTC by mikolajgraczyk

I'm temporarily moving dispatches to the pagination component (because currently it only renders once) so that they only run once. When they are in the PopularMoviesPage and PopularPeoplePage components, they are called unnecessarily every time these components are rendered. (When, for example, we change tabs from people to movies).

2023-03-03 21:24 UTC, marcin10lw requested changes
You did a great job! We just need to update our selectGenresByIds

2023-03-03 21:24 UTC, marcin10lw commented on src/features/movies/moviesSaga.js
> +    yield put(setFetchingToSucces(movies));
Nice you made it into a single put 💪

2023-03-03 21:24 UTC, marcin10lw commented on src/features/movies/moviesSlice.js
> +  if (genres.length > 1) {
I think it should be `genres.length > 0`

2023-03-03 21:24 UTC, marcin10lw commented on src/features/movies/moviesSlice.js
>      return genreIds.map((genreId) => {
During making of actor page i've realized that some of cast movies return genre_ids array with ids that don't match any id in our genres
Now when we map over genreIds it always returns array with the same length and we can get an array like this:
`[undefined, 123, undefined]`.
Later when can't map over such array on Tags.
I suggest changing our selectGenresByIds to look like this:
![image](https://user-images.githubusercontent.com/117176251/222831759-361a15fd-1980-493d-9c3b-8dfd2b35666a.png)

2023-03-04 09:24 UTC, marcin10lw approved these changes

2023-03-04 11:30 UTC, HelkaPL approved these changes
It's looks like legit.
Let's merge it that way.

2023-03-04 17:16 UTC, merged